project_id = "dkxqmiamrnphjoaznpuo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.process-donation]
verify_jwt = false

[functions.confirm-donation]
verify_jwt = false