version: '3.8'

services:
  keila:
    image: pentacent/keila:latest
    container_name: somatech-keila
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      # Database configuration
      DATABASE_URL: postgresql://keila:keila_password@keila-db:5432/keila
      
      # Email configuration (using SMTP for development)
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: ${KEILA_SMTP_USERNAME}
      SMTP_PASSWORD: ${KEILA_SMTP_PASSWORD}
      SMTP_TLS: true
      
      # Application settings
      SECRET_KEY_BASE: ${KEILA_SECRET_KEY_BASE}
      HOST: localhost
      PORT: 4000
      
      # Real estate specific settings
      APP_NAME: "SomaTech Email Campaigns"
      DEFAULT_FROM_EMAIL: "campaigns@somatech.com"
      
    depends_on:
      - keila-db
    networks:
      - somatech-network

  keila-db:
    image: postgres:15
    container_name: somatech-keila-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keila
      POSTGRES_USER: keila
      POSTGRES_PASSWORD: keila_password
    volumes:
      - keila-db-data:/var/lib/postgresql/data
    networks:
      - somatech-network

volumes:
  keila-db-data:

networks:
  somatech-network:
    external: true 