// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkxqmiamrnphjoaznpuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRreHFtaWFtcm5waGpvYXpucHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDQyNTksImV4cCI6MjA2NzA4MDI1OX0.wEGR3XgRlkwt_OKuOm-WS67t-KXreylDQoB3VZmoj-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});